/**
 * Salesdock API scope.
 *
 * The Salesdock API path embeds a scope segment:
 * `https://app.salesdock.nl/api/{domain}/{version}/{scope}/{resource}`.
 *
 * - `user`    — access limited to the authenticated user's own data.
 * - `account` — access across the whole account.
 *
 * Some endpoints hard-code their scope (the SDK handles that internally); for
 * the endpoints that accept either, this value (or a per-call override) is used.
 */
export type Scope = "user" | "account";

/** Production base URL. */
export const PRODUCTION_BASE_URL = "https://app.salesdock.nl";

/** Staging base URL (for development/testing). */
export const STAGING_BASE_URL = "https://app-staging.salesdock.nl";

/** Default API version. */
export const DEFAULT_VERSION = "v1";

/**
 * A minimal, fetch-compatible function signature.
 *
 * Matches the global `fetch` available on Cloudflare Workers, Deno, Bun, modern
 * browsers and Node.js 18+. Provide your own to inject a custom transport
 * (proxies, mocking, instrumentation, ...).
 */
export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

/** Hook invoked before each request leaves the SDK. */
export type RequestHook = (req: {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: string;
}) => void | Promise<void>;

/** Hook invoked after each response is received (before envelope handling). */
export type ResponseHook = (res: {
  method: string;
  url: string;
  status: number;
  durationMs: number;
}) => void | Promise<void>;

/** Configuration for {@link Salesdock}. */
export interface SalesdockConfig {
  /**
   * Your Salesdock account domain (the sub-account/tenant slug), e.g.
   * `"testomgeving"`. This is the `{domain}` segment of every API path.
   */
  domain: string;

  /**
   * Bearer API token. Generated by your account admin and tied to a Salesdock
   * user. May be IP-restricted depending on how it was created.
   */
  token: string;

  /**
   * Default scope for endpoints that accept either `user` or `account`.
   * Endpoints with a fixed scope ignore this. Defaults to `"user"`.
   */
  scope?: Scope;

  /** API version segment. Defaults to `"v1"`. */
  version?: string;

  /**
   * Base URL. Defaults to {@link PRODUCTION_BASE_URL}. Pass
   * {@link STAGING_BASE_URL} for the staging environment, or any custom origin.
   */
  baseUrl?: string;

  /**
   * Custom fetch implementation. Defaults to the global `fetch`. Required if no
   * global `fetch` exists in your runtime.
   */
  fetch?: FetchLike;

  /**
   * Validate API responses against Zod schemas (default `true`). Response
   * schemas use passthrough semantics, so unknown/added fields never cause a
   * failure — only structural/type mismatches do. Set to `false` to skip
   * response validation entirely for maximum throughput.
   */
  validateResponses?: boolean;

  /**
   * Validate request input against Zod schemas before sending (default `true`).
   * Catches mistakes locally as a {@link SalesdockInvalidRequestError} instead
   * of a server round-trip.
   */
  validateRequests?: boolean;

  /**
   * Maximum number of automatic retries for transient failures (HTTP 429, 5xx,
   * and network errors). Defaults to `2`. Set to `0` to disable retries.
   */
  maxRetries?: number;

  /**
   * Base delay in milliseconds for exponential backoff between retries.
   * Defaults to `500`. The `Retry-After` response header (when present) takes
   * precedence over the computed backoff.
   */
  retryDelayMs?: number;

  /**
   * Per-request timeout in milliseconds, enforced with `AbortController`.
   * Defaults to `60000`. Set to `0` to disable the timeout.
   */
  timeout?: number;

  /** Additional headers sent with every request. */
  headers?: Record<string, string>;

  /** Optional hook fired before each request. */
  onRequest?: RequestHook;

  /** Optional hook fired after each response. */
  onResponse?: ResponseHook;

  /**
   * User-Agent appended to the default. Ignored in runtimes that forbid setting
   * the `User-Agent` header (e.g. browsers).
   */
  userAgent?: string;
}

/** Fully-resolved configuration with all defaults applied. */
export interface ResolvedConfig {
  domain: string;
  token: string;
  scope: Scope;
  version: string;
  baseUrl: string;
  fetch: FetchLike;
  validateResponses: boolean;
  validateRequests: boolean;
  maxRetries: number;
  retryDelayMs: number;
  timeout: number;
  headers: Record<string, string>;
  onRequest?: RequestHook;
  onResponse?: ResponseHook;
  userAgent?: string;
}

/** SDK version, surfaced in the default User-Agent. */
export const SDK_VERSION = "0.1.0";

/**
 * Validate user config and apply defaults. Throws a plain `Error` for
 * misconfiguration that must be fixed by the developer (missing domain/token,
 * absent fetch).
 */
export function resolveConfig(config: SalesdockConfig): ResolvedConfig {
  if (!config || typeof config !== "object") {
    throw new Error("Salesdock: configuration object is required.");
  }
  if (!config.domain || typeof config.domain !== "string") {
    throw new Error(
      'Salesdock: `domain` is required (your account sub-domain, e.g. "testomgeving").',
    );
  }
  if (!config.token || typeof config.token !== "string") {
    throw new Error("Salesdock: `token` (Bearer API token) is required.");
  }

  const resolvedFetch = config.fetch ?? globalFetch();
  if (!resolvedFetch) {
    throw new Error(
      "Salesdock: no global `fetch` found in this runtime. Pass a `fetch` implementation in the config.",
    );
  }

  const baseUrl = (config.baseUrl ?? PRODUCTION_BASE_URL).replace(/\/+$/, "");

  return {
    domain: config.domain,
    token: config.token,
    scope: config.scope ?? "user",
    version: config.version ?? DEFAULT_VERSION,
    baseUrl,
    fetch: resolvedFetch,
    validateResponses: config.validateResponses ?? true,
    validateRequests: config.validateRequests ?? true,
    maxRetries: config.maxRetries ?? 2,
    retryDelayMs: config.retryDelayMs ?? 500,
    timeout: config.timeout ?? 60000,
    headers: { ...(config.headers ?? {}) },
    onRequest: config.onRequest,
    onResponse: config.onResponse,
    userAgent: config.userAgent,
  };
}

function globalFetch(): FetchLike | undefined {
  const f = (globalThis as { fetch?: unknown }).fetch;
  return typeof f === "function" ? (f as FetchLike).bind(globalThis) : undefined;
}
